apiVersion: v1
description: A Helm chart for deploying CyberArk Secrets Provider for Kubernetes
name: secrets-provider
version: 1.7.5
home: https://github.com/cyberark/secrets-provider-for-k8s
icon: https://www.cyberark.com/wp-content/uploads/2015/12/cybr-aim.jpg
