{{- if eq .Values.secretsProvider.mode "standalone" }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}
{{- with .Values.labels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
webhooks:
  - name: secrets-provider.cyberark.com
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: {{ .Release.Namespace }}
    clientConfig:
      service:
        name:  {{ .Release.Name }}
        namespace: {{ .Release.Namespace  }}
        path: "/webhook"
        port: 5000
      caBundle: {{ .Values.webhook.ca }}
    rules:
      - operations: [ "CREATE","UPDATE","DELETE" ]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources: ["secrets"]
        scope: "Namespaced"
    failurePolicy: 'Ignore'
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
{{- end }}