{{- if eq .Values.secretsProvider.mode "standalone" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webhook
  namespace: {{ .Release.Namespace }}
{{- with .Values.labels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
data:
  cert.pem: {{ Values.webhook.cert }}
  key.pem: {{ Values.webhook.key }}
type: Opaque
{{- end }}